[project]
name = "b2b-inventory-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "scikit-learn>=1.7.2",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.64.0",
]
